#!/bin/bash

source "$(dirname "$(readlink -f "$0")")/kp_common"

# If we wanted to get to bash shell:
docker run --rm -ti \
	--user "$USER_ID":"$GROUP_ID" \
	-e PATH \
	"${DOCKER_MOUNT_DIRS[@]}" \
	"$IMAGE_ID" \
	bash --init-file /etc/profile

# TODO: we can reuse this image for future runs, for now just clean up after ourselves
docker rmi "$IMAGE_ID"
