#!/bin/bash

# Check if Docker image exists

# Use Directly from Docker hub if not provided:
IMG_NAME="${IMG_NAME:-nishanthmenon/arm-kernel-dev}"

# TBD: If we are using from github -> I need to figure out how to get that working..

# If we are building locally
# IMG_NAME=arm-kernel-dev

# Check if docker exists
docker=`which docker`
if [ -z "$docker" ]; then
	echo "Please install Docker and Image arm-kernel-dev from:" `dirname $0`
	exit 1
fi
dimg=`docker image ls | grep arm-kernel-dev`
if [ -z "$dimg" ]; then
	echo "Please install Docker Image arm-kernel-dev from: cd" `dirname $0` ";make"
	exit 1
fi
ccache=`which ccache`
if [ -z "ccache" ]; then
	if [ ! -d "/tmp/ccache" ]; then
		mkdir /tmp/ccache
	fi
	CCACHEDIR=/tmp/ccache
else
	CCACHEDIR=`ccache -s|grep "cache directory"|sed -e "s/\s\s*/ /g"|cut -d ' ' -f3`
fi
TMP_GITCONFIG=`mktemp`
echo '[user]' >$TMP_GITCONFIG
git config --list|grep ^user|cut -d '.' -f2->>$TMP_GITCONFIG

echo '[core]' >>$TMP_GITCONFIG
git config --list|grep ^core|cut -d '.' -f2->>$TMP_GITCONFIG

DOCKER_MOUNT_DIRS="-v $TMP_GITCONFIG:/workdir/.gitconfig -v /tmp:/tmp -v /opt:/opt -v $CCACHEDIR:/ccache -v $(pwd):/workdir "

# Mount parent directory if its a worktree
GIT_WORKTREE_COMMONDIR=$(git rev-parse --git-common-dir)
if [[ $GIT_WORKTREE_COMMONDIR != ".git" ]]; then
	DOCKER_MOUNT_DIRS+=" -v	$GIT_WORKTREE_COMMONDIR:$GIT_WORKTREE_COMMONDIR "
fi

docker run --rm -ti "$DOCKER_MOUNT_DIRS" "$IMG_NAME"  kernel_patch_verify $*
rm -f $TMP_GITCONFIG
